CREATE TABLE IF NOT EXISTS `form_aec_ros` (
    /* both extended and encounter forms need a last modified date */
    date datetime default NULL comment 'last modified date',
    /* these fields are common to all encounter forms. */
    id bigint(20) NOT NULL auto_increment,
    pid bigint(20) NOT NULL default 0,
    user varchar(5) default NULL,
    groupname varchar(5) default NULL,
    authorized tinyint(4) default NULL,
    activity tinyint(4) default NULL,
    weight_loss varchar(5),
    weight_gain varchar(5),
    fatigue varchar(5),
    -- sleep_problems varchar(5),
	night_sweats varchar(5),
	fevers_chills varchar(5),
	rashes varchar(5),
	hair_skin_nails varchar(5),
	heat_cold_intolerance varchar(5),
	bleeding_bruising varchar(5),
	heavy_menses varchar(5),
    vision_changes varchar(5),
    blurry_vision varchar(5),
    wear_glasses varchar(5),
    floaters varchar(5),
    glaucoma varchar(5),
	cataracts varchar(5),
	watery_itchy_eyes varchar(5),
	dry_eyes varchar(5),
    hearing_loss varchar(5),
    ringing varchar(5),
    roaring varchar(5),
    dizziness varchar(5),
    vertigo varchar(5),
    ear_pain varchar(5),
    ear_drainage varchar(5),
	ear_pressure varchar(5),
	ear_fullness varchar(5),
	pulsing_noises varchar(5),
	wax_buildup varchar(5),
    ear_surgery varchar(5),
    ear_infections varchar(5),
	use_q_tips varchar(5),
	ear_tubes varchar(5),
	recent_hearing_changes varchar(5),
	hearing_up_down varchar(5),
	hearing_aids varchar(5),
	deafness varchar(5),
    allergies varchar(5),
    congestion varchar(5),
    stuffiness varchar(5),
    sinus_pain varchar(5),
    sinus_pressure varchar(5),
    sinus_surgery varchar(5),
    blocked_breathing varchar(5),
    hoarseness varchar(5),
    dryness varchar(5),
    voice_fatigue varchar(5),
    frequent_throat_clearing varchar(5),
    increased_phlegm varchar(5),
    post_nasal_drip varchar(5),
    face_pain varchar(5),
    face_numbness varchar(5),
    twitching varchar(5),
    face_weakness varchar(5),
    lopsided varchar(5),
    neck_pain varchar(5),
    mass varchar(5),
    lump varchar(5),
    goiter varchar(5),
    spine_surgery varchar(5),
    decreased_mobility varchar(5),
    noisy_breathing varchar(5),
    headache varchar(5),
    numbness varchar(5),
    weakness varchar(5),
    walking_problems varchar(5),
    chest_pain varchar(5),
    heart_attack varchar(5),
    heart_failure varchar(5),
    abnormal_rhythm varchar(5),
    breathing_changes varchar(5),
    asthma varchar(5),
    copd varchar(5),
    smoking varchar(5),
    cough varchar(5),
    stomach_pain varchar(5),
    diarrhea varchar(5),
    constipation varchar(5),
    nausea varchar(5),
    vomiting varchar(5),
    cramping varchar(5),
    appetite_changes varchar(5),
    abnormal_lymph_nodes varchar(5),
    rheumatoid_arthritis varchar(5),
    lupus varchar(5),
    sjogrens varchar(5),
    wegeners varchar(5),
    psoriasis varchar(5),
    osteoarthritis varchar(5),
    PRIMARY KEY (id)
) ENGINE=InnoDB;

